Permissions: update output and comments, also call refresh in pre-commit hook

diff --git a/bin/trk b/bin/trk
--- a/bin/trk
+++ b/bin/trk
@@ -322,7 +322,7 @@ permissions_match_stdin() {
 # Add a path to be tracked for permissions
 permissions_mark_command() {
   if [[ $# -lt 1 ]]; then
-    echo "Missing file."
+    echo "Missing file argument"
     exit 1
   fi
 
@@ -348,7 +348,7 @@ permissions_mark_command() {
 # Remove a path from being tracked for permissions
 permissions_unmark_command() {
   if [[ $# -lt 1 ]]; then
-    echo "Missing file."
+    echo "Missing file argument"
     exit 1
   fi
 
@@ -380,13 +380,14 @@ permissions_unmark_command() {
 permissions_apply_command() {
   # Apply the permissions stored in .gitpermissions using setfacl
   if [[ ! -f "$GIT_ROOT/$PERMISSIONS_FILE" ]]; then
-    echo_stderr "No $PERMISSIONS_FILE file found, skipping permission application."
+    echo_stderr "No permissions found, skipping permission application."
     return
   fi
 
-  echo_stderr "Applying stored file permissions from $PERMISSIONS_FILE."
+  echo_stderr "Applying permissions"
 
-  # Apply the permissions using setfacl
+  # Restore file permissions from the $PERMISSIONS_FILE file after checkout
+  # Uses setfacl to restore base ACL entries (owner, group, other).
   (
     set -eu
     cd "$GIT_ROOT"
@@ -398,53 +399,51 @@ permissions_apply_command() {
 #
 # Read the worktree file permissions and update the stored permissions
 permissions_refresh_command() {
-  "$GIT_BIN" hook run pre-commit
-}
-
-hook_pre-commit_command() {
-  # Generate a list of current file permissions in the repository
-  # and save it to .gitpermissions file in the root of the repository.
-  # Uses getfacl to capture base ACL entries only (owner, group, other).
-
-  # Generate the .gitpermissions file using getfacl
-  # Exclude .gitpermissions itself from tracking
-  # Use -z and xargs -0 to handle filenames with spaces
   if [[ ! -f "$GIT_ROOT/$PERMISSIONS_LIST_FILE" ]]; then
-    echo_stderr "No permissions files to track, skipping .gitpermissions update."
+    echo_stderr "No permissions are being tracked."
     return
   fi
 
-  if ! git diff-index --cached --name-only HEAD -z -- | permissions_match_stdin 1>/dev/null && git diff-index --cached --quiet --exit-code HEAD -- "$GIT_ROOT/$PERMISSIONS_LIST_FILE"; then
-    echo_stderr "No tracked files changed, skipping .gitpermissions update." 1>&2
-    return
-  fi
+  echo_stderr "Refreshing tracked permissions"
 
-  echo_stderr "Updating $PERMISSIONS_FILE with current file permissions."
+  # Generate a list of current file permissions in the repository
+  # and save it to $PERMISSIONS_FILE file in the repository.
+  # Uses getfacl to capture base ACL entries only (owner, group, other).
   (
     set -eu
     cd "$GIT_ROOT"
-    xargs -a "$GIT_ROOT/$PERMISSIONS_LIST_FILE" getfacl -R --access > "$GIT_ROOT/$PERMISSIONS_FILE"
+    xargs -d '\n' -a "$GIT_ROOT/$PERMISSIONS_LIST_FILE" getfacl -R --access > "$GIT_ROOT/$PERMISSIONS_FILE"
   )
 
   git add "$GIT_ROOT/$PERMISSIONS_FILE"
+}
+
+hook_pre-commit_command() {
+  if [[ ! -f "$GIT_ROOT/$PERMISSIONS_LIST_FILE" ]]; then
+    return
+  fi
+
+  # Check if any of the tracked files have changed permissions or if the permissions list has changed
+  if ! git diff-index --cached --name-only HEAD -z -- | permissions_match_stdin 1>/dev/null && git diff-index --cached --quiet --exit-code HEAD -- "$GIT_ROOT/$PERMISSIONS_LIST_FILE"; then
+    return
+  fi
+
+  permissions_refresh_command
 }
 
 hook_post-checkout_command() {
   previous_head="$1"
   new_head="$2"
 
-  # Restore file permissions from the .gitpermissions file after checkout
-  # Uses setfacl to restore base ACL entries (owner, group, other).
 
   if [[ ! -f "$GIT_ROOT/$PERMISSIONS_FILE" ]]; then
-    echo_stderr "No $PERMISSIONS_FILE file found, skipping permission application."
     return
   fi
 
-  # Always apply if null-ref was given (e.g. clone)
+  # Always apply if null-ref was given (e.g. git clone)
   if ! echo "$previous_head" | grep -qx '0\+'; then
+    # Check if any of the tracked files have changed permissions or if the permissions list has changed
     if ! git diff "$previous_head" "$new_head" --name-only -z -- | permissions_match_stdin 1>/dev/null && git diff --quiet --exit-code "$previous_head" "$new_head" -- "$GIT_ROOT/$PERMISSIONS_FILE"; then
-      echo_stderr "Tracked files did not change, skipping permission application."
       return
     fi
   fi
@@ -483,7 +482,7 @@ permissions_status_command() {
 # Patterns are gitattributes patterns, similar to .gitignore.
 mark_command() {
   if [[ $# -lt 1 ]]; then
-    echo "Missing file or pattern."
+    echo "Missing file or pattern argument"
     exit 1
   fi
 
@@ -516,7 +515,7 @@ mark_command() {
 # Remove encryption mark
 unmark_command() {
   if [[ $# -lt 1 ]]; then
-    echo "Missing file or pattern."
+    echo "Missing file or pattern argument"
     exit 1
   fi
 
